import string

VARIABLE_NAME_START_CHARACTERS = string.ascii_letters + "_"
VARIABLE_NAME_CHARACTERS = VARIABLE_NAME_START_CHARACTERS + string.digits

NUMBER_START_CHARACTERS = string.digits
NUMBER_CHARACTERS = string.digits + "."

TUPLE_START_CHAR = '('
TUPLE_END_CHAR = ')'
BLOCK_START_CHAR = '{'
BLOCK_END_CHAR = '}'
TABLE_START_CHAR = '['
TABLE_END_CHAR = ']'

ENCLOSING_CHARACTERS =	TUPLE_START_CHAR +\
						TUPLE_END_CHAR +\
						BLOCK_START_CHAR +\
						BLOCK_END_CHAR +\
						TABLE_START_CHAR +\
						TABLE_END_CHAR

STRING_CHAR = '"'
COMMENT_CHAR = '#'
EOL_CHAR = ';'
SEPARATOR_CHAR = ','
NEWLINE_CHAR = '\n'

WHITESPACE = string.whitespace


TYPE_NULL = 0
TYPE_TERM = 1
TYPE_BOOLEAN = 2
TYPE_NUMBER = 3
TYPE_STRING = 4
TYPE_COMMENT = 5
TYPE_WHITESPACE = 6
TYPE_OPERATOR = 7
TYPE_FUNCTION = 8
TYPE_SUBROUTINE = 9
TYPE_ASSIGN = 10
TYPE_GOTO = 11
TYPE_GOSUB = 12
TYPE_EOL = 13
TYPE_SEPARATOR = 14
TYPE_ENCLOSED = 15
TYPE_BLOCK_START = 16
TYPE_BLOCK_END = 17
TYPE_OTHER = 18


LITERAL_TYPES = (
	TYPE_BOOLEAN,
	TYPE_NUMBER,
	TYPE_STRING
)


TYPE_NAMES = (
	"NULL",
	"TERM",
	"BOOLEAN",
	"NUMBER",
	"STRING",
	"COMMENT",
	"WHITESPACE",
	"OPERATOR",
	"FUNCTION",
	"SUBROUTINE",
	"CALL",
	"GOTO",
	"GOSUB",
	"EOL",
	"SEPARATOR",
	"ENCLOSED",
	"BLOCK START",
	"BLOCK END",
	"OTHER"
)


LEFT_TO_RIGHT = 0
RIGHT_TO_LEFT = 1


