import string

STACK_MAX = 4
VAR_MAX = 6
TOKEN_MAX = 64

VARIABLE_NAME_START_CHARACTERS = string.ascii_letters + "_"
VARIABLE_NAME_CHARACTERS = VARIABLE_NAME_START_CHARACTERS + string.digits

NUMBER_START_CHARACTERS = string.digits
NUMBER_CHARACTERS = string.digits + "."

TUPLE_START_CHAR = '('
TUPLE_END_CHAR = ')'
BLOCK_START_CHAR = '{'
BLOCK_END_CHAR = '}'
TABLE_START_CHAR = '['
TABLE_END_CHAR = ']'

ENCLOSING_CHARACTERS =	TUPLE_START_CHAR +\
						TUPLE_END_CHAR +\
						BLOCK_START_CHAR +\
						BLOCK_END_CHAR +\
						TABLE_START_CHAR +\
						TABLE_END_CHAR

STRING_CHAR = '"'
COMMENT_CHAR = '#'
EOL_CHAR = ';'
SEPARATOR_CHAR = ','
NEWLINE_CHAR = '\n'

WHITESPACE = string.whitespace

TYPE_NULL = 0
TYPE_COMMENT = 1
TYPE_WHITESPACE = 2
TYPE_TERM = 3
TYPE_OPERATOR = 4
TYPE_FUNCTION = 5
TYPE_GOTO = 6
TYPE_GOSUB = 7
TYPE_NUMBER = 8
TYPE_STRING = 9
TYPE_EOL = 10
TYPE_SEPARATOR = 11
TYPE_ENCLOSED = 12
TYPE_BLOCK_START = 13
TYPE_BLOCK_END = 14
TYPE_OTHER = 15

LEFT_TO_RIGHT = 0
RIGHT_TO_LEFT = 1

MISC_KEYWORDS = [
	"else"
]


